[workspace]
resolver = "3"
default-members = ["frontends/iced_client"]
members = [ "shared",
    "frontends/iced_client"
]

[workspace.package]
edition = "2024"
rust-version = "1.90"

[workspace.dependencies]

shared = { path = "shared"}
iced_client = { path = "frontends/iced_client" }


crux_core = "0.20"
tokio = { version = "1", features = ["macros"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
derive_more = { version = "2", features = ["deref", "deref_mut","constructor"] }
